var ttAbove       = false;        // tooltip above mousepointer? Alternative: true
var ttBgColor     = "#E7F0F5";
var ttBgImg       = "";           // path to background image;
var ttBorderColor = "#476687";
var ttBorderWidth = 1;
var ttClickClose  = false;
var ttDelay       = 100;          // time span until tooltip shows up [milliseconds]
var ttFontColor   = "#082F57";
var ttFontFace    = "arial,helvetica,sans-serif";
var ttFontSize    = ".85em";
var ttFontWeight  = "normal";     // alternative: "bold";
var ttLeft        = false;        // tooltip on the left of the mouse? Alternative: true
var ttOffsetX     = 12;           // horizontal offset of left-top corner from mousepointer
var ttOffsetY     = 15;           // vertical offset                   "
var ttOpacity     = 100;          // opacity of tooltip in percent (must be integer between 0 and 100)
var ttPadding     = 4;            // spacing between border and content
var ttShadowColor = "";
var ttShadowWidth = 0;
var ttStatic      = false;        // tooltip NOT move with the mouse? Alternative: true
var ttSticky      = false;        // do NOT hide tooltip on mouseout? Alternative: true
var ttTemp        = 0;            // time span after which the tooltip disappears; 0 (zero) means "infinite timespan"
var ttTextAlign   = "left";
var ttTitleColor  = "#ffffff";    // color of caption text
var ttWidth       = 150;
